[package]
name = "aoc_2025_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
reqwest = { version = "0.12", features=["blocking"] }

[[bin]]
name = "scripts_get_input"
path = "src/bin/scripts/get_input.rs"